from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsUI(object):
    def setupUi(self, SettingsUI):
        SettingsUI.setObjectName("SettingsUI")
        SettingsUI.resize(911, 422)
        SettingsUI.setMinimumSize(QtCore.QSize(911, 422))
        SettingsUI.setMaximumSize(QtCore.QSize(911, 422))
        self.gridLayout = QtWidgets.QGridLayout(SettingsUI)
        self.gridLayout.setObjectName("gridLayout")
        self.usrAccHold = QtWidgets.QLineEdit(SettingsUI)
        self.usrAccHold.setObjectName("usrAccHold")
        self.gridLayout.addWidget(self.usrAccHold, 3, 5, 1, 2)
        self.usrFocus = QtWidgets.QLineEdit(SettingsUI)
        self.usrFocus.setObjectName("usrFocus")
        self.gridLayout.addWidget(self.usrFocus, 7, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(SettingsUI)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 3, 1, 2)
        self.companyLogo = QtWidgets.QLabel(SettingsUI)
        self.companyLogo.setMinimumSize(QtCore.QSize(200, 80))
        self.companyLogo.setStyleSheet("border: 3px solid;\n"
"border-color: rgb(181, 181, 181);\n"
"border-radius: 10px;")
        self.companyLogo.setObjectName("companyLogo")
        self.gridLayout.addWidget(self.companyLogo, 9, 5, 1, 2)
        self.btnBrowse = QtWidgets.QPushButton(SettingsUI)
        self.btnBrowse.setMinimumSize(QtCore.QSize(0, 80))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBrowse.setIcon(icon)
        self.btnBrowse.setObjectName("btnBrowse")
        self.gridLayout.addWidget(self.btnBrowse, 9, 3, 1, 2)
        self.label_9 = QtWidgets.QLabel(SettingsUI)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 3, 1, 2)
        self.usrBankCode = QtWidgets.QLineEdit(SettingsUI)
        self.usrBankCode.setObjectName("usrBankCode")
        self.gridLayout.addWidget(self.usrBankCode, 5, 5, 1, 2)
        self.companyName = QtWidgets.QLineEdit(SettingsUI)
        self.companyName.setObjectName("companyName")
        self.gridLayout.addWidget(self.companyName, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(SettingsUI)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 3, 1, 1)
        self.usrAccNum = QtWidgets.QLineEdit(SettingsUI)
        self.usrAccNum.setObjectName("usrAccNum")
        self.gridLayout.addWidget(self.usrAccNum, 4, 5, 1, 2)
        self.label_7 = QtWidgets.QLabel(SettingsUI)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 3, 1, 2)
        self.usrButton = QtWidgets.QLineEdit(SettingsUI)
        self.usrButton.setObjectName("usrButton")
        self.gridLayout.addWidget(self.usrButton, 2, 5, 1, 2)
        self.label_11 = QtWidgets.QLabel(SettingsUI)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(SettingsUI)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 1, 1, 2)
        self.label = QtWidgets.QLabel(SettingsUI)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 2, 7)
        self.usrRef = QtWidgets.QLineEdit(SettingsUI)
        self.usrRef.setObjectName("usrRef")
        self.gridLayout.addWidget(self.usrRef, 6, 5, 1, 2)
        self.label_2 = QtWidgets.QLabel(SettingsUI)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(SettingsUI)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 3, 1, 2)
        self.btnAdd = QtWidgets.QPushButton(SettingsUI)
        self.btnAdd.setMinimumSize(QtCore.QSize(0, 55))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon1)
        self.btnAdd.setIconSize(QtCore.QSize(13, 13))
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 7, 6, 2, 1)
        self.usrMessage = QtWidgets.QTextEdit(SettingsUI)
        self.usrMessage.setObjectName("usrMessage")
        self.gridLayout.addWidget(self.usrMessage, 4, 1, 6, 2)
        self.listFocus = QtWidgets.QComboBox(SettingsUI)
        self.listFocus.setObjectName("listFocus")
        self.gridLayout.addWidget(self.listFocus, 8, 5, 1, 1)
        self.btnBack = QtWidgets.QPushButton(SettingsUI)
        self.btnBack.setMinimumSize(QtCore.QSize(0, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon2)
        self.btnBack.setObjectName("btnBack")
        self.gridLayout.addWidget(self.btnBack, 10, 6, 1, 1)
        self.retranslateUi(SettingsUI)
        QtCore.QMetaObject.connectSlotsByName(SettingsUI)

        # Call Functions
        self.btnBack.clicked.connect(lambda: toMenu(self, SettingsUI))

    def retranslateUi(self, SettingsUI):
        _translate = QtCore.QCoreApplication.translate
        SettingsUI.setWindowTitle(_translate("SettingsUI", "Settings"))
        self.label_4.setText(_translate("SettingsUI", "Account Holder:"))
        self.companyLogo.setText(_translate("SettingsUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#888a85;\">LOGO</span></p></body></html>"))
        self.btnBrowse.setText(_translate("SettingsUI", " BROWSE"))
        self.label_9.setText(_translate("SettingsUI", "Reference:"))
        self.label_3.setText(_translate("SettingsUI", "Bank:"))
        self.label_7.setText(_translate("SettingsUI", "Account Number:"))
        self.label_11.setText(_translate("SettingsUI", "Focus:"))
        self.label_10.setText(_translate("SettingsUI", "Statement Thank you message:"))
        self.label.setText(_translate("SettingsUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; color:#0f3362;\">SETTINGS</span></p></body></html>"))
        self.label_2.setText(_translate("SettingsUI", "Company Name:"))
        self.label_8.setText(_translate("SettingsUI", "Branch Code:"))
        self.btnAdd.setText(_translate("SettingsUI", " ADD"))
        self.btnBack.setText(_translate("SettingsUI", " Back"))

from tutoringMain import Ui_tutoringMainUI

def toMenu(self,SettingsUI):
    self.window = QtWidgets.QWidget()
    self.ui = Ui_tutoringMainUI()
    self.ui.setupUi(self.window)
    self.window.show()
    SettingsUI.hide()
    # print("button clicked") #Debug event

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingsUI = QtWidgets.QWidget()
    ui = Ui_SettingsUI()
    ui.setupUi(SettingsUI)
    SettingsUI.show()
    sys.exit(app.exec_())
