from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_statementUI(object):
    def setupUi(self, statementUI):
        #UI Setup
        statementUI.setObjectName("statementUI")
        statementUI.resize(899, 1673)
        statementUI.showMaximized()
        self.gridLayout = QtWidgets.QGridLayout(statementUI)
        self.gridLayout.setObjectName("gridLayout")
        self.selFrom = QtWidgets.QDateEdit(statementUI)
        self.selFrom.setMaximumSize(QtCore.QSize(110, 16777215))
        self.selFrom.setObjectName("selFrom")
        self.gridLayout.addWidget(self.selFrom, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 5, 2, 3)
        self.label_4 = QtWidgets.QLabel(statementUI)
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(statementUI)
        self.label_2.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.btnGenerate = QtWidgets.QPushButton(statementUI)
        self.btnGenerate.setMinimumSize(QtCore.QSize(0, 55))
        self.btnGenerate.setMaximumSize(QtCore.QSize(150, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnGenerate.setIcon(icon)
        self.btnGenerate.setObjectName("btnGenerate")
        self.gridLayout.addWidget(self.btnGenerate, 1, 4, 2, 1)
        self.btnBack = QtWidgets.QPushButton(statementUI)
        self.btnBack.setMinimumSize(QtCore.QSize(100, 55))
        self.btnBack.setMaximumSize(QtCore.QSize(150, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon1)
        self.btnBack.setObjectName("btnBack")
        self.gridLayout.addWidget(self.btnBack, 4, 6, 1, 1)
        self.btnPrint = QtWidgets.QPushButton(statementUI)
        self.btnPrint.setMinimumSize(QtCore.QSize(100, 55))
        self.btnPrint.setMaximumSize(QtCore.QSize(150, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrint.setIcon(icon2)
        self.btnPrint.setObjectName("btnPrint")
        self.gridLayout.addWidget(self.btnPrint, 4, 7, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 6)
        self.scrollArea = QtWidgets.QScrollArea(statementUI)
        self.scrollArea.setStyleSheet("background: rgb(46, 52, 54)")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 879, 1453))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 0, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(840, 1188))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(840, 1188))
        self.scrollArea_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 838, 1186))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.clientContact = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.clientContact.setMinimumSize(QtCore.QSize(300, 0))
        self.clientContact.setObjectName("clientContact")
        self.gridLayout_3.addWidget(self.clientContact, 2, 2, 1, 2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_2)
        self.scrollArea_3.setMinimumSize(QtCore.QSize(400, 180))
        self.scrollArea_3.setMaximumSize(QtCore.QSize(400, 180))
        self.scrollArea_3.setStyleSheet("")
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 398, 178))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_16 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 1)
        self.usrBank = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.usrBank.setObjectName("usrBank")
        self.gridLayout_4.addWidget(self.usrBank, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 4, 0, 1, 1)
        self.usrAccNum = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.usrAccNum.setObjectName("usrAccNum")
        self.gridLayout_4.addWidget(self.usrAccNum, 2, 1, 1, 1)
        self.usrRef = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.usrRef.setObjectName("usrRef")
        self.gridLayout_4.addWidget(self.usrRef, 4, 1, 1, 1)
        self.usrBranch = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.usrBranch.setObjectName("usrBranch")
        self.gridLayout_4.addWidget(self.usrBranch, 3, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 3, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 1, 0, 1, 1)
        self.usrAccName = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.usrAccName.setObjectName("usrAccName")
        self.gridLayout_4.addWidget(self.usrAccName, 1, 1, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.addWidget(self.scrollArea_3, 4, 0, 3, 3)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 4, 4, 1, 1)
        self.usrMessage = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.usrMessage.setMinimumSize(QtCore.QSize(0, 50))
        self.usrMessage.setObjectName("usrMessage")
        self.gridLayout_3.addWidget(self.usrMessage, 7, 0, 1, 7)
        self.companyLogo = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.companyLogo.setMinimumSize(QtCore.QSize(200, 80))
        self.companyLogo.setStyleSheet("border: 3px solid;border-color: rgb(181, 181, 181);border-radius: 10px;")
        self.companyLogo.setObjectName("companyLogo")
        self.gridLayout_3.addWidget(self.companyLogo, 0, 4, 1, 3)
        self.statementTable = QtWidgets.QTableWidget(self.scrollAreaWidgetContents_2)
        self.statementTable.setObjectName("statementTable")
        self.statementTable.setColumnCount(4)
        self.statementTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.statementTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.statementTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.statementTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.statementTable.setHorizontalHeaderItem(3, item)
        self.gridLayout_3.addWidget(self.statementTable, 3, 0, 1, 7)
        self.totalCost = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.totalCost.setMaximumSize(QtCore.QSize(16777215, 20))
        self.totalCost.setObjectName("totalCost")
        self.gridLayout_3.addWidget(self.totalCost, 5, 5, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 5, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setMinimumSize(QtCore.QSize(140, 0))
        self.label_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setMinimumSize(QtCore.QSize(140, 0))
        self.label_7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setMinimumSize(QtCore.QSize(500, 80))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 70))
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 4)
        self.totalHours = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.totalHours.setMaximumSize(QtCore.QSize(16777215, 20))
        self.totalHours.setObjectName("totalHours")
        self.gridLayout_3.addWidget(self.totalHours, 4, 5, 1, 2)
        self.companyName = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.companyName.setObjectName("companyName")
        self.gridLayout_3.addWidget(self.companyName, 1, 4, 2, 3)
        self.clientName = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.clientName.setMinimumSize(QtCore.QSize(300, 0))
        self.clientName.setObjectName("clientName")
        self.gridLayout_3.addWidget(self.clientName, 1, 2, 1, 2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_2.addWidget(self.scrollArea_2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 3, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 3, 0, 1, 8)
        self.label_3 = QtWidgets.QLabel(statementUI)
        self.label_3.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.selTo = QtWidgets.QDateEdit(statementUI)
        self.selTo.setMaximumSize(QtCore.QSize(110, 16777215))
        self.selTo.setObjectName("selTo")
        self.gridLayout.addWidget(self.selTo, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(statementUI)
        self.label.setMinimumSize(QtCore.QSize(0, 70))
        self.label.setMaximumSize(QtCore.QSize(16777215, 70))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 8)
        self.selClient = QtWidgets.QComboBox(statementUI)
        self.selClient.setObjectName("selClient")
        self.gridLayout.addWidget(self.selClient, 1, 1, 1, 3)
        self.retranslateUi(statementUI)
        QtCore.QMetaObject.connectSlotsByName(statementUI)
        #Call Functions
        self.btnBack.clicked.connect(lambda: toMenu(self,statementUI))

    def retranslateUi(self, statementUI):
        _translate = QtCore.QCoreApplication.translate
        statementUI.setWindowTitle(_translate("statementUI", "Statement"))
        self.label_4.setText(_translate("statementUI", "<html><head/><body><p align=\"center\">- TO -</p></body></html>"))
        self.label_2.setText(_translate("statementUI", "Select Client:"))
        self.btnGenerate.setText(_translate("statementUI", " GENERATE"))
        self.btnBack.setText(_translate("statementUI", " BACK"))
        self.btnPrint.setText(_translate("statementUI", " PRINT"))
        self.clientContact.setText(_translate("statementUI", "Number"))
        self.label_16.setText(_translate("statementUI", "<html><head/><body><p><span style=\" font-weight:600;\">BANK NAME:</span></p></body></html>"))
        self.usrBank.setText(_translate("statementUI", "BANK NAME HERE"))
        self.label_24.setText(_translate("statementUI", "<html><head/><body><p><span style=\" font-weight:600;\">REFERENCE:</span></p></body></html>"))
        self.usrAccNum.setText(_translate("statementUI", "ACCOUNT NUMBER HERE"))
        self.usrRef.setText(_translate("statementUI", "REFERENCE HERE"))
        self.usrBranch.setText(_translate("statementUI", "BRANCH HERE"))
        self.label_22.setText(_translate("statementUI", "<html><head/><body><p><span style=\" font-weight:600;\">BRANCH:</span></p></body></html>"))
        self.label_20.setText(_translate("statementUI", "<html><head/><body><p><span style=\" font-weight:600;\">ACCOUNT NUMBER:</span></p></body></html>"))
        self.label_18.setText(_translate("statementUI", "<html><head/><body><p><span style=\" font-weight:600;\">ACCOUNT HOLDER:</span></p></body></html>"))
        self.usrAccName.setText(_translate("statementUI", "ACCOUNT NAME HERE"))
        self.label_12.setText(_translate("statementUI", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600; color:#0e3262;\">TOTAL HOURS:</span></p></body></html>"))
        self.usrMessage.setText(_translate("statementUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">THANK YOU MESSAGE HERE</span></p></body></html>"))
        self.companyLogo.setText(_translate("statementUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt; font-weight:600; color:#888a85;\">LOGO</span></p></body></html>"))
        item = self.statementTable.horizontalHeaderItem(0)
        item.setText(_translate("statementUI", "Day"))
        item = self.statementTable.horizontalHeaderItem(1)
        item.setText(_translate("statementUI", "Descripition"))
        item = self.statementTable.horizontalHeaderItem(2)
        item.setText(_translate("statementUI", "Time"))
        item = self.statementTable.horizontalHeaderItem(3)
        item.setText(_translate("statementUI", "Rate"))
        self.totalCost.setText(_translate("statementUI", "<html><head/><body><p align=\"right\">R999999.99</p></body></html>"))
        self.label_8.setText(_translate("statementUI", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600; color:#0e3262;\">TOTAL COST:</span></p></body></html>"))
        self.label_6.setText(_translate("statementUI", "Client Name:"))
        self.label_7.setText(_translate("statementUI", "Contact Number:"))
        self.label_5.setText(_translate("statementUI", "<html><head/><body><p><span style=\" font-size:36pt; color:#0e3262;\">STATEMENT</span></p></body></html>"))
        self.totalHours.setText(_translate("statementUI", "<html><head/><body><p align=\"right\">99 Hrs</p></body></html>"))
        self.companyName.setText(_translate("statementUI", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Company Name</span></p></body></html>"))
        self.clientName.setText(_translate("statementUI", "Name"))
        self.label_3.setText(_translate("statementUI", "Select Month:"))
        self.label.setText(_translate("statementUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; color:#0e3262;\">STATEMENT</span></p></body></html>"))

from tutoringMain import Ui_tutoringMainUI

def toMenu(self,statementUI):
    self.window = QtWidgets.QWidget()
    self.ui = Ui_tutoringMainUI()
    self.ui.setupUi(self.window)
    self.window.show()
    statementUI.hide()
    # print("button clicked") #Debug event

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    statementUI = QtWidgets.QWidget()
    ui = Ui_statementUI()
    ui.setupUi(statementUI)
    statementUI.show()
    sys.exit(app.exec_())

