from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_studentsUI(object):
    def setupUi(self, studentsUI):
        #UI Setup
        studentsUI.setObjectName("studentsUI")
        studentsUI.resize(851, 624)
        studentsUI.setMinimumSize(QtCore.QSize(851, 624))
        studentsUI.setMaximumSize(QtCore.QSize(851, 624))
        self.gridLayout_2 = QtWidgets.QGridLayout(studentsUI)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.studentName = QtWidgets.QLineEdit(studentsUI)
        self.studentName.setObjectName("studentName")
        self.gridLayout_2.addWidget(self.studentName, 1, 3, 1, 2)
        self.label_13 = QtWidgets.QLabel(studentsUI)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 10, 0, 1, 1)
        self.btnBack = QtWidgets.QPushButton(studentsUI)
        self.btnBack.setMinimumSize(QtCore.QSize(128, 50))
        self.btnBack.setMaximumSize(QtCore.QSize(128, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon)
        self.btnBack.setIconSize(QtCore.QSize(20, 20))
        self.btnBack.setObjectName("btnBack")
        self.gridLayout_2.addWidget(self.btnBack, 15, 0, 1, 1)
        self.parentContact = QtWidgets.QLineEdit(studentsUI)
        self.parentContact.setObjectName("parentContact")
        self.gridLayout_2.addWidget(self.parentContact, 5, 3, 1, 2)
        self.label_6 = QtWidgets.QLabel(studentsUI)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 2)
        self.lcdTime = QtWidgets.QLCDNumber(studentsUI)
        self.lcdTime.setMinimumSize(QtCore.QSize(100, 40))
        self.lcdTime.setInputMethodHints(QtCore.Qt.ImhTime)
        self.lcdTime.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdTime.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lcdTime.setSmallDecimalPoint(False)
        self.lcdTime.setDigitCount(4)
        self.lcdTime.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcdTime.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdTime.setProperty("value", 1200.0)
        self.lcdTime.setProperty("intValue", 1200)
        self.lcdTime.setObjectName("lcdTime")
        self.gridLayout_2.addWidget(self.lcdTime, 10, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(studentsUI)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(studentsUI)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(studentsUI)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 10, 3, 1, 1)
        self.studentGrade = QtWidgets.QSpinBox(studentsUI)
        self.studentGrade.setObjectName("studentGrade")
        self.gridLayout_2.addWidget(self.studentGrade, 2, 3, 1, 2)
        self.parentName = QtWidgets.QLineEdit(studentsUI)
        self.parentName.setObjectName("parentName")
        self.gridLayout_2.addWidget(self.parentName, 4, 3, 1, 2)
        self.rate = QtWidgets.QSpinBox(studentsUI)
        self.rate.setObjectName("rate")
        self.gridLayout_2.addWidget(self.rate, 6, 3, 1, 2)
        self.studentFocus = QtWidgets.QComboBox(studentsUI)
        self.studentFocus.setObjectName("studentFocus")
        self.gridLayout_2.addWidget(self.studentFocus, 3, 3, 1, 2)
        self.label = QtWidgets.QLabel(studentsUI)
        self.label.setMinimumSize(QtCore.QSize(0, 60))
        self.label.setMaximumSize(QtCore.QSize(16777215, 60))
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 8)
        self.spinDuration = QtWidgets.QDoubleSpinBox(studentsUI)
        self.spinDuration.setDecimals(1)
        self.spinDuration.setMinimum(0.5)
        self.spinDuration.setMaximum(24.0)
        self.spinDuration.setSingleStep(0.5)
        self.spinDuration.setProperty("value", 1.0)
        self.spinDuration.setObjectName("spinDuration")
        self.gridLayout_2.addWidget(self.spinDuration, 10, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(studentsUI)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 11, 0, 1, 5)
        self.sliderTime = QtWidgets.QScrollBar(studentsUI)
        self.sliderTime.setMinimumSize(QtCore.QSize(0, 40))
        self.sliderTime.setMaximumSize(QtCore.QSize(16777215, 40))
        self.sliderTime.setInputMethodHints(QtCore.Qt.ImhTime)
        self.sliderTime.setMaximum(48)
        self.sliderTime.setPageStep(1)
        self.sliderTime.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTime.setObjectName("sliderTime")
        self.gridLayout_2.addWidget(self.sliderTime, 14, 0, 1, 5)
        self.label_8 = QtWidgets.QLabel(studentsUI)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(studentsUI)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.label_10 = QtWidgets.QLabel(studentsUI)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(studentsUI)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 13, 0, 1, 5)
        self.listStudents = QtWidgets.QListWidget(studentsUI)
        self.listStudents.setObjectName("listStudents")
        self.gridLayout_2.addWidget(self.listStudents, 1, 5, 14, 3)
        self.label_9 = QtWidgets.QLabel(studentsUI)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 0, 1, 1)
        self.groupDay = QtWidgets.QGroupBox(studentsUI)
        self.groupDay.setObjectName("groupDay")
        self.gridLayout = QtWidgets.QGridLayout(self.groupDay)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkWed = QtWidgets.QCheckBox(self.groupDay)
        self.checkWed.setObjectName("checkWed")
        self.gridLayout_3.addWidget(self.checkWed, 2, 0, 1, 1)
        self.checkTue = QtWidgets.QCheckBox(self.groupDay)
        self.checkTue.setObjectName("checkTue")
        self.gridLayout_3.addWidget(self.checkTue, 1, 0, 1, 1)
        self.checkMon = QtWidgets.QCheckBox(self.groupDay)
        self.checkMon.setObjectName("checkMon")
        self.gridLayout_3.addWidget(self.checkMon, 0, 0, 1, 1)
        self.checkThur = QtWidgets.QCheckBox(self.groupDay)
        self.checkThur.setObjectName("checkThur")
        self.gridLayout_3.addWidget(self.checkThur, 3, 0, 1, 1)
        self.checkFri = QtWidgets.QCheckBox(self.groupDay)
        self.checkFri.setObjectName("checkFri")
        self.gridLayout_3.addWidget(self.checkFri, 0, 1, 1, 1)
        self.checkSat = QtWidgets.QCheckBox(self.groupDay)
        self.checkSat.setObjectName("checkSat")
        self.gridLayout_3.addWidget(self.checkSat, 1, 1, 1, 1)
        self.checkSun = QtWidgets.QCheckBox(self.groupDay)
        self.checkSun.setObjectName("checkSun")
        self.gridLayout_3.addWidget(self.checkSun, 2, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupDay, 7, 0, 3, 5)
        self.btnAdd = QtWidgets.QPushButton(studentsUI)
        self.btnAdd.setMinimumSize(QtCore.QSize(175, 50))
        self.btnAdd.setMaximumSize(QtCore.QSize(175, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/user add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon1)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout_2.addWidget(self.btnAdd, 15, 7, 1, 1)
        self.btnRemove = QtWidgets.QPushButton(studentsUI)
        self.btnRemove.setMinimumSize(QtCore.QSize(175, 50))
        self.btnRemove.setMaximumSize(QtCore.QSize(175, 50))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemove.setIcon(icon2)
        self.btnRemove.setObjectName("btnRemove")
        self.gridLayout_2.addWidget(self.btnRemove, 15, 5, 1, 2)
        self.retranslateUi(studentsUI)
        QtCore.QMetaObject.connectSlotsByName(studentsUI)

        # Call Functions
        self.btnBack.clicked.connect(lambda: toMenu(self, studentsUI))

    def retranslateUi(self, studentsUI):
        _translate = QtCore.QCoreApplication.translate
        studentsUI.setWindowTitle(_translate("studentsUI", "Students"))
        self.label_13.setText(_translate("studentsUI", "Set Slot Duration"))
        self.btnBack.setText(_translate("studentsUI", "BACK"))
        self.label_6.setText(_translate("studentsUI", "Student Grade:"))
        self.label_5.setText(_translate("studentsUI", "Parent Full Name:"))
        self.label_7.setText(_translate("studentsUI", "Focus:"))
        self.label_2.setText(_translate("studentsUI", "Student Full Name:"))
        self.label.setText(_translate("studentsUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; color:#0e3262;\">STUDENTS</span></p></body></html>"))
        self.label_12.setText(_translate("studentsUI", "Set Time:"))
        self.label_8.setText(_translate("studentsUI", "Parent Contact:"))
        self.label_4.setText(_translate("studentsUI", "00:00"))
        self.label_10.setText(_translate("studentsUI", "<html><head/><body><p align=\"center\">12:00</p></body></html>"))
        self.label_11.setText(_translate("studentsUI", "<html><head/><body><p align=\"right\">24:00</p></body></html>"))
        self.label_9.setText(_translate("studentsUI", "Rate:"))
        self.groupDay.setTitle(_translate("studentsUI", "Select Days:"))
        self.checkWed.setText(_translate("studentsUI", "Wednesday"))
        self.checkTue.setText(_translate("studentsUI", "Tueday"))
        self.checkMon.setText(_translate("studentsUI", "Monday"))
        self.checkThur.setText(_translate("studentsUI", "Thursday"))
        self.checkFri.setText(_translate("studentsUI", "Friday"))
        self.checkSat.setText(_translate("studentsUI", "Saturday"))
        self.checkSun.setText(_translate("studentsUI", "Sunday"))
        self.btnAdd.setText(_translate("studentsUI", " ADD"))
        self.btnRemove.setText(_translate("studentsUI", " REMOVE"))

from tutoringMain import Ui_tutoringMainUI

def toMenu(self,studentsUI):
    self.window = QtWidgets.QWidget()
    self.ui = Ui_tutoringMainUI()
    self.ui.setupUi(self.window)
    self.window.show()
    studentsUI.hide()
    # print("button clicked") #Debug event

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentsUI = QtWidgets.QWidget()
    ui = Ui_studentsUI()
    ui.setupUi(studentsUI)
    studentsUI.show()
    sys.exit(app.exec_())
