from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_studentsUI(object):
    def setupUi(self, studentsUI):
        studentsUI.setObjectName("studentsUI")
        studentsUI.resize(742, 396)
        studentsUI.setMinimumSize(QtCore.QSize(742, 396))
        studentsUI.setMaximumSize(QtCore.QSize(742, 396))
        self.gridLayout = QtWidgets.QGridLayout(studentsUI)
        self.gridLayout.setObjectName("gridLayout")
        self.btnRemove = QtWidgets.QPushButton(studentsUI)
        self.btnRemove.setMinimumSize(QtCore.QSize(128, 50))
        self.btnRemove.setMaximumSize(QtCore.QSize(128, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemove.setIcon(icon)
        self.btnRemove.setObjectName("btnRemove")
        self.gridLayout.addWidget(self.btnRemove, 9, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(studentsUI)
        self.label_5.setMinimumSize(QtCore.QSize(130, 25))
        self.label_5.setMaximumSize(QtCore.QSize(130, 25))
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(studentsUI)
        self.label_6.setMinimumSize(QtCore.QSize(130, 26))
        self.label_6.setMaximumSize(QtCore.QSize(130, 26))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.parentName = QtWidgets.QLineEdit(studentsUI)
        self.parentName.setMinimumSize(QtCore.QSize(262, 25))
        self.parentName.setMaximumSize(QtCore.QSize(262, 25))
        self.parentName.setObjectName("parentName")
        self.gridLayout.addWidget(self.parentName, 4, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(studentsUI)
        self.label_7.setMinimumSize(QtCore.QSize(130, 25))
        self.label_7.setMaximumSize(QtCore.QSize(130, 25))
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(studentsUI)
        self.label_3.setMinimumSize(QtCore.QSize(130, 25))
        self.label_3.setMaximumSize(QtCore.QSize(130, 25))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.rate = QtWidgets.QSpinBox(studentsUI)
        self.rate.setMinimumSize(QtCore.QSize(262, 26))
        self.rate.setMaximumSize(QtCore.QSize(262, 26))
        self.rate.setObjectName("rate")
        self.gridLayout.addWidget(self.rate, 6, 1, 1, 2)
        self.btnAdd = QtWidgets.QPushButton(studentsUI)
        self.btnAdd.setMinimumSize(QtCore.QSize(130, 50))
        self.btnAdd.setMaximumSize(QtCore.QSize(130, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/user add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon1)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 9, 1, 1, 1)
        self.listStudents = QtWidgets.QListWidget(studentsUI)
        self.listStudents.setObjectName("listStudents")
        self.gridLayout.addWidget(self.listStudents, 1, 3, 9, 3)
        self.label_8 = QtWidgets.QLabel(studentsUI)
        self.label_8.setMinimumSize(QtCore.QSize(130, 25))
        self.label_8.setMaximumSize(QtCore.QSize(130, 25))
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.studentGrade = QtWidgets.QSpinBox(studentsUI)
        self.studentGrade.setMinimumSize(QtCore.QSize(262, 26))
        self.studentGrade.setMaximumSize(QtCore.QSize(262, 26))
        self.studentGrade.setObjectName("studentGrade")
        self.gridLayout.addWidget(self.studentGrade, 2, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(studentsUI)
        self.label_9.setMinimumSize(QtCore.QSize(130, 26))
        self.label_9.setMaximumSize(QtCore.QSize(130, 26))
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.lblSlot = QtWidgets.QLabel(studentsUI)
        self.lblSlot.setObjectName("lblSlot")
        self.gridLayout.addWidget(self.lblSlot, 8, 1, 1, 2)
        self.studentFocus = QtWidgets.QComboBox(studentsUI)
        self.studentFocus.setMinimumSize(QtCore.QSize(262, 25))
        self.studentFocus.setMaximumSize(QtCore.QSize(262, 25))
        self.studentFocus.setObjectName("studentFocus")
        self.gridLayout.addWidget(self.studentFocus, 3, 1, 1, 2)
        self.parentContact = QtWidgets.QLineEdit(studentsUI)
        self.parentContact.setMinimumSize(QtCore.QSize(262, 25))
        self.parentContact.setMaximumSize(QtCore.QSize(262, 25))
        self.parentContact.setObjectName("parentContact")
        self.gridLayout.addWidget(self.parentContact, 5, 1, 1, 2)
        self.btnBack = QtWidgets.QPushButton(studentsUI)
        self.btnBack.setMinimumSize(QtCore.QSize(128, 50))
        self.btnBack.setMaximumSize(QtCore.QSize(128, 50))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon2)
        self.btnBack.setIconSize(QtCore.QSize(20, 20))
        self.btnBack.setObjectName("btnBack")
        self.gridLayout.addWidget(self.btnBack, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(studentsUI)
        self.label.setMinimumSize(QtCore.QSize(0, 80))
        self.label.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 6)
        self.label_2 = QtWidgets.QLabel(studentsUI)
        self.label_2.setMinimumSize(QtCore.QSize(130, 25))
        self.label_2.setMaximumSize(QtCore.QSize(130, 25))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.studentName = QtWidgets.QLineEdit(studentsUI)
        self.studentName.setMinimumSize(QtCore.QSize(262, 25))
        self.studentName.setMaximumSize(QtCore.QSize(262, 25))
        self.studentName.setObjectName("studentName")
        self.gridLayout.addWidget(self.studentName, 1, 1, 1, 2)
        self.btnSchedule = QtWidgets.QPushButton(studentsUI)
        self.btnSchedule.setMinimumSize(QtCore.QSize(0, 30))
        self.btnSchedule.setMaximumSize(QtCore.QSize(16777215, 30))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Resources/clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSchedule.setIcon(icon3)
        self.btnSchedule.setObjectName("btnSchedule")
        self.gridLayout.addWidget(self.btnSchedule, 7, 1, 1, 2)

        self.retranslateUi(studentsUI)
        QtCore.QMetaObject.connectSlotsByName(studentsUI)

    def retranslateUi(self, studentsUI):
        _translate = QtCore.QCoreApplication.translate
        studentsUI.setWindowTitle(_translate("studentsUI", "Students"))
        self.btnRemove.setText(_translate("studentsUI", " REMOVE"))
        self.label_5.setText(_translate("studentsUI", "Parent Full Name:"))
        self.label_6.setText(_translate("studentsUI", "Student Grade:"))
        self.label_7.setText(_translate("studentsUI", "Focus:"))
        self.label_3.setText(_translate("studentsUI", "Time Slot:"))
        self.btnAdd.setText(_translate("studentsUI", " ADD"))
        self.label_8.setText(_translate("studentsUI", "Parent Contact:"))
        self.label_9.setText(_translate("studentsUI", "Rate:"))
        self.lblSlot.setText(_translate("studentsUI", "Choose a slot"))
        self.btnBack.setText(_translate("studentsUI", "BACK"))
        self.label.setText(_translate("studentsUI", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt; color:#0e3262;\">STUDENTS</span></p></body></html>"))
        self.label_2.setText(_translate("studentsUI", "Student Full Name:"))
        self.btnSchedule.setText(_translate("studentsUI", " SCHEDULE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentsUI = QtWidgets.QWidget()
    ui = Ui_studentsUI()
    ui.setupUi(studentsUI)
    studentsUI.show()
    sys.exit(app.exec_())

